"""empty message

Revision ID: fb83e4f8ebad
Revises: d11caf10e34b
Create Date: 2025-02-18 16:25:07.921235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fb83e4f8ebad'
down_revision = 'd11caf10e34b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('faccion', sa.String(length=80), nullable=True))
        batch_op.drop_column('facciom')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('person', schema=None) as batch_op:
        batch_op.add_column(sa.Column('facciom', sa.VARCHAR(length=80), autoincrement=False, nullable=True))
        batch_op.drop_column('faccion')

    # ### end Alembic commands ###
